image: node:latest

cache:
  paths:
    - UniHub.Client/Client/node_modules/

stages:
  - build
  
build:
  stage: build
  script:
    cd UniHub.Client/Client &&
    npm install &&
    ./node_modules/@angular/cli/bin/ng build
