version: '2'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwertyui
    expose:
      - "5432"

  db_ui:
    image: adminer
    links:
      - db
    ports:
      - "8080:8080"

  web-api:
    build:
      context: ../UniHub.WebApi
      dockerfile: Dockerfile
    expose: 
      - "5000"
    links:
      - db:db

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - web-api
