version: '2'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwertyui
    expose:
      - "5432"

  db_ui:
    image: adminer
    links:
      - db
    ports:
      - "8080:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    ports:
      - 9200:9200
    volumes:
      - ./share/elasticsearch/data:/usr/share/elasticsearch/data
      - ./share/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks: [elastic]
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.0
    ports:
      - 5601:5601
    networks: [elastic]

  web-api:
    build:
      context: ../UniHub.WebApi
      dockerfile: Dockerfile
    expose: 
      - "5000"
    links:
      - db:db

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - web-api

networks:
  elastic: