// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniHub.WebApi.DataAccess;

namespace UniHub.WebApi.Migrations
{
    [DbContext(typeof(UniHubDbContext))]
    [Migration("20191010170206_RefactorFieldNames2")]
    partial class RefactorFieldNames2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("PostId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.AnswerVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnswerId");

                    b.Property<int>("UserId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("UserId");

                    b.ToTable("AnswerVotes");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountryId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnswerId");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Description");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("PostId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc");

                    b.Property<string>("Description");

                    b.Property<string>("FullTitle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(7);

                    b.Property<int>("UniversityId");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnswerId");

                    b.Property<int?>("CommentId");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc");

                    b.Property<int>("FileTypeId");

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.Property<int>("PostId");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("CommentId");

                    b.HasIndex("FileTypeId");

                    b.HasIndex("PostId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.FileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("FileTypes");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("Number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("YearStart");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("GivenAt");

                    b.Property<int>("GroupId");

                    b.Property<DateTime>("LastVisit");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("PostLocationTypeId");

                    b.Property<int>("PostValueTypeId");

                    b.Property<int>("Semester");

                    b.Property<int>("SubjectId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.Property<int>("VotesCount");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("PostLocationTypeId");

                    b.HasIndex("PostValueTypeId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.PostLocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("PostLocationTypes");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.PostValueType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("PostValueTypes");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.PostVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PostId");

                    b.Property<int>("UserId");

                    b.Property<int>("VoteTypeId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoteTypeId");

                    b.ToTable("PostVotes");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.PostVoteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("PostVoteTypes");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<DateTime>("ExpiredAt");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<string>("Token");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.RoleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("RoleTypes");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc");

                    b.Property<string>("Description");

                    b.Property<int>("FacultyId");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("TeacherId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("UniversityId");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<int>("CityId");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc");

                    b.Property<string>("Description");

                    b.Property<string>("FullTitle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(7);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<decimal>("CurrencyCount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("DeletedAtUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool>("IsValidated");

                    b.Property<DateTime>("LastVisitedAtUtc");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(84);

                    b.Property<int>("RoleId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.UserAvailablePost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PostId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAvailablePosts");
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Answer", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Post", "Post")
                        .WithMany("Answers")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.AnswerVote", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Answer", "Answer")
                        .WithMany("Votes")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.City", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Comment", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Answer")
                        .WithMany("Comments")
                        .HasForeignKey("AnswerId");

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Faculty", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.File", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Answer")
                        .WithMany("Files")
                        .HasForeignKey("AnswerId");

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Comment")
                        .WithMany("Files")
                        .HasForeignKey("CommentId");

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.FileType", "Type")
                        .WithMany("Files")
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Post", "Post")
                        .WithMany("Files")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Post", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Group", "Group")
                        .WithMany("Posts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.PostLocationType", "PostLocationType")
                        .WithMany("Posts")
                        .HasForeignKey("PostLocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.PostValueType", "PostValueType")
                        .WithMany("Posts")
                        .HasForeignKey("PostValueTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Subject", "Subject")
                        .WithMany("Posts")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.PostVote", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.PostVoteType", "VoteType")
                        .WithMany("PostActions")
                        .HasForeignKey("VoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.RefreshToken", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Subject", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Faculty", "Faculty")
                        .WithMany("Subjects")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.Teacher", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.University", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.City", "City")
                        .WithMany("Universities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.User", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.RoleType", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniHub.WebApi.ModelLayer.Entities.UserAvailablePost", b =>
                {
                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.Post", "Post")
                        .WithMany("UserAvailablePosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniHub.WebApi.ModelLayer.Entities.User", "User")
                        .WithMany("UserAvailablePosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
